version: '3.8'
services:
  frontend:
    build:
      context: ./e-invoice-frontend
      dockerfile: Dockerfile
    volumes:
      - ./e-invoice-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    restart: unless-stopped
  backend:
    build:
      context: ./e-invoice-backend
      dockerfile: Dockerfile
    volumes:
      - ./e-invoice-backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: npm run start:dev
    restart: unless-stopped